# $schema: schema.json
load:
  # The term component provides a modern TUI-based interactive terminal for
  # inspecting and interacting with objects published to Sen buses.
  - name: term
    group: 2
    open:
      - my.tutorial
