[supervisord]
nodaemon=true

[program:influxdb]
command=/usr/bin/influxd
autostart=true
autorestart=true
stderr_logfile=/var/log/influxdb.err.log
stdout_logfile=/var/log/influxdb.out.log

[program:telegraf]
command=/usr/bin/telegraf
autostart=true
autorestart=true
stderr_logfile=/var/log/telegraf.err.log
stdout_logfile=/var/log/telegraf.out.log

[program:grafana]
command=/usr/sbin/grafana-server --homepath=/usr/share/grafana/
autostart=true
autorestart=true
stderr_logfile=/var/log/grafana.err.log
stdout_logfile=/var/log/grafana.out.log
