var annotated_dup =
[
    [ "pybind11", "namespacepybind11.html", [
      [ "detail", "namespacepybind11_1_1detail.html", [
        [ "type_caster< sen::ObjectId >", "structpybind11_1_1detail_1_1type__caster_3_01sen_1_1_object_id_01_4.html", "structpybind11_1_1detail_1_1type__caster_3_01sen_1_1_object_id_01_4" ]
      ] ]
    ] ],
    [ "sen", "namespacesen.html", [
      [ "db", "namespacesen_1_1db.html", [
        [ "Annotation", "classsen_1_1db_1_1_annotation.html", "classsen_1_1db_1_1_annotation" ],
        [ "Creation", "classsen_1_1db_1_1_creation.html", "classsen_1_1db_1_1_creation" ],
        [ "Cursor", "classsen_1_1db_1_1_cursor.html", "classsen_1_1db_1_1_cursor" ],
        [ "Deletion", "classsen_1_1db_1_1_deletion.html", "classsen_1_1db_1_1_deletion" ],
        [ "End", "group__db.html#classsen_1_1db_1_1_end", null ],
        [ "Event", "classsen_1_1db_1_1_event.html", "classsen_1_1db_1_1_event" ],
        [ "Input", "classsen_1_1db_1_1_input.html", "classsen_1_1db_1_1_input" ],
        [ "Keyframe", "classsen_1_1db_1_1_keyframe.html", "classsen_1_1db_1_1_keyframe" ],
        [ "KeyframeIndex", "group__db.html#structsen_1_1db_1_1_keyframe_index", "group__db_structsen_1_1db_1_1_keyframe_index" ],
        [ "ObjectIndexDef", "group__db.html#structsen_1_1db_1_1_object_index_def", "group__db_structsen_1_1db_1_1_object_index_def" ],
        [ "ObjectInfo", "group__db.html#structsen_1_1db_1_1_object_info", "group__db_structsen_1_1db_1_1_object_info" ],
        [ "Output", "classsen_1_1db_1_1_output.html", "classsen_1_1db_1_1_output" ],
        [ "PropertyChange", "classsen_1_1db_1_1_property_change.html", "classsen_1_1db_1_1_property_change" ],
        [ "Snapshot", "classsen_1_1db_1_1_snapshot.html", "classsen_1_1db_1_1_snapshot" ]
      ] ],
      [ "detail", "namespacesen_1_1detail.html", [
        [ "TemplatedBaseTypeDispatcher", "namespacesen_1_1detail.html#structsen_1_1detail_1_1_templated_base_type_dispatcher", "namespacesen_1_1detail_structsen_1_1detail_1_1_templated_base_type_dispatcher_dup" ],
        [ "TemplatedBaseTypeDispatcher< T, BaseClassType, true >", "namespacesen_1_1detail.html#structsen_1_1detail_1_1_templated_base_type_dispatcher_3_01_t_00_01_base_class_type_00_01true_01_4", "namespacesen_1_1detail_structsen_1_1detail_1_1_templated_base_type_dispatcher_3_01_t_00_01_base_class_type_00_01true_01_4_dup" ]
      ] ],
      [ "kernel", "namespacesen_1_1kernel.html", [
        [ "Bootloader", "classsen_1_1kernel_1_1_bootloader.html", "classsen_1_1kernel_1_1_bootloader" ],
        [ "BusId", "structsen_1_1kernel_1_1_bus_id.html", "structsen_1_1kernel_1_1_bus_id" ],
        [ "Component", "classsen_1_1kernel_1_1_component.html", "classsen_1_1kernel_1_1_component" ],
        [ "ComponentContext", "group__kernel.html#structsen_1_1kernel_1_1_component_context", "group__kernel_structsen_1_1kernel_1_1_component_context" ],
        [ "ComponentMonitoringInfo", "namespacesen_1_1kernel.html#structsen_1_1kernel_1_1_component_monitoring_info", "namespacesen_1_1kernel_structsen_1_1kernel_1_1_component_monitoring_info_dup" ],
        [ "ConfigGetter", "classsen_1_1kernel_1_1_config_getter.html", "classsen_1_1kernel_1_1_config_getter" ],
        [ "InitApi", "classsen_1_1kernel_1_1_init_api.html", "classsen_1_1kernel_1_1_init_api" ],
        [ "Kernel", "classsen_1_1kernel_1_1_kernel.html", "classsen_1_1kernel_1_1_kernel" ],
        [ "KernelApi", "classsen_1_1kernel_1_1_kernel_api.html", "classsen_1_1kernel_1_1_kernel_api" ],
        [ "KernelConfig", "classsen_1_1kernel_1_1_kernel_config.html", "classsen_1_1kernel_1_1_kernel_config" ],
        [ "KernelMonitoringInfo", "namespacesen_1_1kernel.html#structsen_1_1kernel_1_1_kernel_monitoring_info", "namespacesen_1_1kernel_structsen_1_1kernel_1_1_kernel_monitoring_info_dup" ],
        [ "LoadApi", "classsen_1_1kernel_1_1_load_api.html", "classsen_1_1kernel_1_1_load_api" ],
        [ "PackageManager", "classsen_1_1kernel_1_1_package_manager.html", "classsen_1_1kernel_1_1_package_manager" ],
        [ "ParticipantAddr", "group__kernel.html#structsen_1_1kernel_1_1_participant_addr", "group__kernel_structsen_1_1kernel_1_1_participant_addr" ],
        [ "PreloadApi", "classsen_1_1kernel_1_1_preload_api.html", "classsen_1_1kernel_1_1_preload_api" ],
        [ "RegistrationApi", "classsen_1_1kernel_1_1_registration_api.html", "classsen_1_1kernel_1_1_registration_api" ],
        [ "RunApi", "classsen_1_1kernel_1_1_run_api.html", "classsen_1_1kernel_1_1_run_api" ],
        [ "SessionInfoProvider", "classsen_1_1kernel_1_1_session_info_provider.html", "classsen_1_1kernel_1_1_session_info_provider" ],
        [ "SessionsDiscoverer", "classsen_1_1kernel_1_1_sessions_discoverer.html", "classsen_1_1kernel_1_1_sessions_discoverer" ],
        [ "SourceInfo", "classsen_1_1kernel_1_1_source_info.html", "classsen_1_1kernel_1_1_source_info" ],
        [ "TestComponent", "classsen_1_1kernel_1_1_test_component.html", "classsen_1_1kernel_1_1_test_component" ],
        [ "TestKernel", "classsen_1_1kernel_1_1_test_kernel.html", "classsen_1_1kernel_1_1_test_kernel" ],
        [ "Tracer", "classsen_1_1kernel_1_1_tracer.html", "classsen_1_1kernel_1_1_tracer" ],
        [ "Transport", "classsen_1_1kernel_1_1_transport.html", "classsen_1_1kernel_1_1_transport" ],
        [ "TransportListener", "classsen_1_1kernel_1_1_transport_listener.html", "classsen_1_1kernel_1_1_transport_listener" ],
        [ "TransportStats", "group__kernel.html#structsen_1_1kernel_1_1_transport_stats", "group__kernel_structsen_1_1kernel_1_1_transport_stats" ],
        [ "UniqueByteBufferManager", "classsen_1_1kernel_1_1_unique_byte_buffer_manager.html", "classsen_1_1kernel_1_1_unique_byte_buffer_manager" ],
        [ "UnloadApi", "classsen_1_1kernel_1_1_unload_api.html", "classsen_1_1kernel_1_1_unload_api" ]
      ] ],
      [ "lang", "namespacesen_1_1lang.html", [
        [ "BusNameStatement", "group__lang.html#structsen_1_1lang_1_1_bus_name_statement", "group__lang_structsen_1_1lang_1_1_bus_name_statement" ],
        [ "Chunk", "classsen_1_1lang_1_1_chunk.html", "classsen_1_1lang_1_1_chunk" ],
        [ "ClassAnnotations", "group__lang.html#structsen_1_1lang_1_1_class_annotations", "group__lang_structsen_1_1lang_1_1_class_annotations" ],
        [ "CodeLocation", "group__lang.html#structsen_1_1lang_1_1_code_location", "group__lang_structsen_1_1lang_1_1_code_location" ],
        [ "ErrorReporter", "classsen_1_1lang_1_1_error_reporter.html", "classsen_1_1lang_1_1_error_reporter" ],
        [ "FomDocument", "namespacesen_1_1lang.html#structsen_1_1lang_1_1_fom_document", "namespacesen_1_1lang_structsen_1_1lang_1_1_fom_document_dup" ],
        [ "FomDocumentSet", "classsen_1_1lang_1_1_fom_document_set.html", "classsen_1_1lang_1_1_fom_document_set" ],
        [ "FomParser", "classsen_1_1lang_1_1_fom_parser.html", "classsen_1_1lang_1_1_fom_parser" ],
        [ "ParsedDoc", "namespacesen_1_1lang.html#structsen_1_1lang_1_1_parsed_doc", "namespacesen_1_1lang_structsen_1_1lang_1_1_parsed_doc_dup" ],
        [ "QueryStatement", "group__lang.html#structsen_1_1lang_1_1_query_statement", "group__lang_structsen_1_1lang_1_1_query_statement" ],
        [ "ResolverContext", "group__lang.html#structsen_1_1lang_1_1_resolver_context", "group__lang_structsen_1_1lang_1_1_resolver_context" ],
        [ "StlArgStatement", "group__lang.html#structsen_1_1lang_1_1_stl_arg_statement", "group__lang_structsen_1_1lang_1_1_stl_arg_statement" ],
        [ "StlArrayStatement", "group__lang.html#structsen_1_1lang_1_1_stl_array_statement", "group__lang_structsen_1_1lang_1_1_stl_array_statement" ],
        [ "StlAttribute", "group__lang.html#structsen_1_1lang_1_1_stl_attribute", "group__lang_structsen_1_1lang_1_1_stl_attribute" ],
        [ "StlBetweenExpr", "group__lang.html#structsen_1_1lang_1_1_stl_between_expr", "group__lang_structsen_1_1lang_1_1_stl_between_expr" ],
        [ "StlBinaryExpr", "group__lang.html#structsen_1_1lang_1_1_stl_binary_expr", "group__lang_structsen_1_1lang_1_1_stl_binary_expr" ],
        [ "StlClassStatement", "group__lang.html#structsen_1_1lang_1_1_stl_class_statement", "group__lang_structsen_1_1lang_1_1_stl_class_statement" ],
        [ "StlEnumeratorStatement", "group__lang.html#structsen_1_1lang_1_1_stl_enumerator_statement", "group__lang_structsen_1_1lang_1_1_stl_enumerator_statement" ],
        [ "StlEnumStatement", "group__lang.html#structsen_1_1lang_1_1_stl_enum_statement", "group__lang_structsen_1_1lang_1_1_stl_enum_statement" ],
        [ "StlEventStatement", "group__lang.html#structsen_1_1lang_1_1_stl_event_statement", "group__lang_structsen_1_1lang_1_1_stl_event_statement" ],
        [ "StlExpr", "group__lang.html#structsen_1_1lang_1_1_stl_expr", "group__lang_structsen_1_1lang_1_1_stl_expr" ],
        [ "StlFunctionStatement", "group__lang.html#structsen_1_1lang_1_1_stl_function_statement", "group__lang_structsen_1_1lang_1_1_stl_function_statement" ],
        [ "StlGroupingExpr", "group__lang.html#structsen_1_1lang_1_1_stl_grouping_expr", "group__lang_structsen_1_1lang_1_1_stl_grouping_expr" ],
        [ "StlImportStatement", "group__lang.html#structsen_1_1lang_1_1_stl_import_statement", "group__lang_structsen_1_1lang_1_1_stl_import_statement" ],
        [ "StlInExpr", "group__lang.html#structsen_1_1lang_1_1_stl_in_expr", "group__lang_structsen_1_1lang_1_1_stl_in_expr" ],
        [ "StlInterfaceStatement", "group__lang.html#structsen_1_1lang_1_1_stl_interface_statement", "group__lang_structsen_1_1lang_1_1_stl_interface_statement" ],
        [ "StlLiteralExpr", "group__lang.html#structsen_1_1lang_1_1_stl_literal_expr", "group__lang_structsen_1_1lang_1_1_stl_literal_expr" ],
        [ "StlLogicalExpr", "group__lang.html#structsen_1_1lang_1_1_stl_logical_expr", "group__lang_structsen_1_1lang_1_1_stl_logical_expr" ],
        [ "StlOptionalTypeStatement", "group__lang.html#structsen_1_1lang_1_1_stl_optional_type_statement", "group__lang_structsen_1_1lang_1_1_stl_optional_type_statement" ],
        [ "StlPackageStatement", "group__lang.html#structsen_1_1lang_1_1_stl_package_statement", "group__lang_structsen_1_1lang_1_1_stl_package_statement" ],
        [ "StlParser", "classsen_1_1lang_1_1_stl_parser.html", "classsen_1_1lang_1_1_stl_parser" ],
        [ "StlQuantityStatement", "group__lang.html#structsen_1_1lang_1_1_stl_quantity_statement", "group__lang_structsen_1_1lang_1_1_stl_quantity_statement" ],
        [ "StlResolver", "classsen_1_1lang_1_1_stl_resolver.html", "classsen_1_1lang_1_1_stl_resolver" ],
        [ "StlScanner", "classsen_1_1lang_1_1_stl_scanner.html", "classsen_1_1lang_1_1_stl_scanner" ],
        [ "StlSequenceStatement", "group__lang.html#structsen_1_1lang_1_1_stl_sequence_statement", "group__lang_structsen_1_1lang_1_1_stl_sequence_statement" ],
        [ "StlStructFieldStatement", "group__lang.html#structsen_1_1lang_1_1_stl_struct_field_statement", "group__lang_structsen_1_1lang_1_1_stl_struct_field_statement" ],
        [ "StlStructStatement", "group__lang.html#structsen_1_1lang_1_1_stl_struct_statement", "group__lang_structsen_1_1lang_1_1_stl_struct_statement" ],
        [ "StlToken", "structsen_1_1lang_1_1_stl_token.html", "structsen_1_1lang_1_1_stl_token" ],
        [ "StlTypeAliasStatement", "group__lang.html#structsen_1_1lang_1_1_stl_type_alias_statement", "group__lang_structsen_1_1lang_1_1_stl_type_alias_statement" ],
        [ "StlTypeNameStatement", "group__lang.html#structsen_1_1lang_1_1_stl_type_name_statement", "group__lang_structsen_1_1lang_1_1_stl_type_name_statement" ],
        [ "StlUnaryExpr", "group__lang.html#structsen_1_1lang_1_1_stl_unary_expr", "group__lang_structsen_1_1lang_1_1_stl_unary_expr" ],
        [ "StlVariableExpr", "group__lang.html#structsen_1_1lang_1_1_stl_variable_expr", "group__lang_structsen_1_1lang_1_1_stl_variable_expr" ],
        [ "StlVariantElement", "group__lang.html#structsen_1_1lang_1_1_stl_variant_element", "group__lang_structsen_1_1lang_1_1_stl_variant_element" ],
        [ "StlVariantStatement", "group__lang.html#structsen_1_1lang_1_1_stl_variant_statement", "group__lang_structsen_1_1lang_1_1_stl_variant_statement" ],
        [ "StlVarStatement", "group__lang.html#structsen_1_1lang_1_1_stl_var_statement", "group__lang_structsen_1_1lang_1_1_stl_var_statement" ],
        [ "TypeSet", "group__lang.html#structsen_1_1lang_1_1_type_set", "group__lang_structsen_1_1lang_1_1_type_set" ],
        [ "TypeSetContext", "classsen_1_1lang_1_1_type_set_context.html", "classsen_1_1lang_1_1_type_set_context" ],
        [ "TypeSettings", "group__lang.html#structsen_1_1lang_1_1_type_settings", "group__lang_structsen_1_1lang_1_1_type_settings" ],
        [ "VariantAccessError", "group__lang.html#structsen_1_1lang_1_1_variant_access_error", null ],
        [ "VM", "classsen_1_1lang_1_1_v_m.html", "classsen_1_1lang_1_1_v_m" ]
      ] ],
      [ "std_util", "namespacesen_1_1std__util.html", [
        [ "detail", "namespacesen_1_1std__util_1_1detail.html", [
          [ "IsInPlaceType", "structsen_1_1std__util_1_1detail_1_1_is_in_place_type.html", null ],
          [ "IsInPlaceType< std::in_place_type_t< T > >", "structsen_1_1std__util_1_1detail_1_1_is_in_place_type_3_01std_1_1in__place__type__t_3_01_t_01_4_01_4.html", null ],
          [ "MoveOnlyFunctionBase", "classsen_1_1std__util_1_1detail_1_1_move_only_function_base.html", "classsen_1_1std__util_1_1detail_1_1_move_only_function_base" ],
          [ "MoveOnlyFunctionImpl", "namespacesen_1_1std__util_1_1detail.html#classsen_1_1std__util_1_1detail_1_1_move_only_function_impl", null ],
          [ "MoveOnlyFunctionImpl< ResultType(ArgTypes...) GENERATE_WITH_CV GENERATE_WITH_REF NOEXCEPT_SPECIFIER >", "classsen_1_1std__util_1_1detail_1_1_move_only_function_impl_3_01_result_type_07_arg_types_8_8_8_e1791c2d0ac6611c5c45d4bd5dec2ff0.html", "classsen_1_1std__util_1_1detail_1_1_move_only_function_impl_3_01_result_type_07_arg_types_8_8_8_e1791c2d0ac6611c5c45d4bd5dec2ff0" ]
        ] ],
        [ "IsInstantiationOf", "structsen_1_1std__util_1_1_is_instantiation_of.html", null ],
        [ "IsInstantiationOf< Template, Template< Args... > >", "structsen_1_1std__util_1_1_is_instantiation_of_3_01_template_00_01_template_3_01_args_8_8_8_01_4_01_4.html", null ],
        [ "ReportPolicyAssertion", "structsen_1_1std__util_1_1_report_policy_assertion.html", null ],
        [ "ReportPolicyIgnore", "structsen_1_1std__util_1_1_report_policy_ignore.html", null ],
        [ "ReportPolicyLog", "structsen_1_1std__util_1_1_report_policy_log.html", null ],
        [ "ReportPolicyTrace", "structsen_1_1std__util_1_1_report_policy_trace.html", null ]
      ] ],
      [ "test", "namespacesen_1_1test.html", [
        [ "runtime", "namespacesen_1_1test_1_1runtime.html", [
          [ "TestClassImpl", "classsen_1_1test_1_1runtime_1_1_test_class_impl.html", "classsen_1_1test_1_1runtime_1_1_test_class_impl" ],
          [ "TesterImpl", "classsen_1_1test_1_1runtime_1_1_tester_impl.html", "classsen_1_1test_1_1runtime_1_1_tester_impl" ]
        ] ],
        [ "BufferedTestReader", "classsen_1_1test_1_1_buffered_test_reader.html", "classsen_1_1test_1_1_buffered_test_reader" ],
        [ "TestClassImpl", "classsen_1_1test_1_1_test_class_impl.html", "classsen_1_1test_1_1_test_class_impl" ],
        [ "TesterImpl", "classsen_1_1test_1_1_tester_impl.html", "classsen_1_1test_1_1_tester_impl" ],
        [ "TestReader", "classsen_1_1test_1_1_test_reader.html", "classsen_1_1test_1_1_test_reader" ],
        [ "TestWriter", "classsen_1_1test_1_1_test_writer.html", "classsen_1_1test_1_1_test_writer" ]
      ] ],
      [ "util", "namespacesen_1_1util.html", [
        [ "Acceleration", "group__dr.html#structsen_1_1util_1_1_acceleration", "group__dr_structsen_1_1util_1_1_acceleration" ],
        [ "AngularAcceleration", "group__dr.html#structsen_1_1util_1_1_angular_acceleration", "group__dr_structsen_1_1util_1_1_angular_acceleration" ],
        [ "AngularVelocity", "group__dr.html#structsen_1_1util_1_1_angular_velocity", "group__dr_structsen_1_1util_1_1_angular_velocity" ],
        [ "DeadReckoner", "classsen_1_1util_1_1_dead_reckoner.html", "classsen_1_1util_1_1_dead_reckoner" ],
        [ "DeadReckonerBase", "classsen_1_1util_1_1_dead_reckoner_base.html", "classsen_1_1util_1_1_dead_reckoner_base" ],
        [ "DeadReckonerTemplateBase", "classsen_1_1util_1_1_dead_reckoner_template_base.html", "classsen_1_1util_1_1_dead_reckoner_template_base" ],
        [ "DrConfig", "group__dr.html#structsen_1_1util_1_1_dr_config", "group__dr_structsen_1_1util_1_1_dr_config" ],
        [ "DrThreshold", "group__dr.html#structsen_1_1util_1_1_dr_threshold", "group__dr_structsen_1_1util_1_1_dr_threshold" ],
        [ "GeodeticSituation", "group__dr.html#structsen_1_1util_1_1_geodetic_situation", "group__dr_structsen_1_1util_1_1_geodetic_situation" ],
        [ "GeodeticWorldLocation", "group__dr.html#structsen_1_1util_1_1_geodetic_world_location", "group__dr_structsen_1_1util_1_1_geodetic_world_location" ],
        [ "HaversineData", "namespacesen_1_1util.html#structsen_1_1util_1_1_haversine_data", "namespacesen_1_1util_structsen_1_1util_1_1_haversine_data_dup" ],
        [ "IteratorRange", "structsen_1_1util_1_1_iterator_range.html", "structsen_1_1util_1_1_iterator_range" ],
        [ "Location", "group__dr.html#structsen_1_1util_1_1_location", "group__dr_structsen_1_1util_1_1_location" ],
        [ "LockedRangeAdapter", "classsen_1_1util_1_1_locked_range_adapter.html", "classsen_1_1util_1_1_locked_range_adapter" ],
        [ "Mat3", "classsen_1_1util_1_1_mat3.html", "classsen_1_1util_1_1_mat3" ],
        [ "Orientation", "group__dr.html#structsen_1_1util_1_1_orientation", "group__dr_structsen_1_1util_1_1_orientation" ],
        [ "Quat", "classsen_1_1util_1_1_quat.html", "classsen_1_1util_1_1_quat" ],
        [ "SettableDeadReckoner", "classsen_1_1util_1_1_settable_dead_reckoner.html", "classsen_1_1util_1_1_settable_dead_reckoner" ],
        [ "Situation", "group__dr.html#structsen_1_1util_1_1_situation", "group__dr_structsen_1_1util_1_1_situation" ],
        [ "SmartPtrIteratorAdapter", "structsen_1_1util_1_1_smart_ptr_iterator_adapter.html", "structsen_1_1util_1_1_smart_ptr_iterator_adapter" ],
        [ "Vec3", "classsen_1_1util_1_1_vec3.html", "classsen_1_1util_1_1_vec3" ],
        [ "Velocity", "group__dr.html#structsen_1_1util_1_1_velocity", "group__dr_structsen_1_1util_1_1_velocity" ]
      ] ],
      [ "AliasSpec", "structsen_1_1_alias_spec.html", "structsen_1_1_alias_spec" ],
      [ "AliasType", "classsen_1_1_alias_type.html", "classsen_1_1_alias_type" ],
      [ "Arg", "structsen_1_1_arg.html", "structsen_1_1_arg" ],
      [ "ArrayTraitsBase", "structsen_1_1_array_traits_base.html", null ],
      [ "BasicTraits", "structsen_1_1_basic_traits.html", null ],
      [ "BigEndian", "namespacesen.html#structsen_1_1_big_endian", null ],
      [ "BufferWriter", "classsen_1_1_buffer_writer.html", "classsen_1_1_buffer_writer" ],
      [ "BusSpec", "group__obj.html#structsen_1_1_bus_spec", "group__obj_structsen_1_1_bus_spec" ],
      [ "Callable", "classsen_1_1_callable.html", "classsen_1_1_callable" ],
      [ "CallableSpec", "structsen_1_1_callable_spec.html", "structsen_1_1_callable_spec" ],
      [ "Callback", "classsen_1_1_callback.html", "classsen_1_1_callback" ],
      [ "ClassSpec", "group__types.html#structsen_1_1_class_spec", "group__types_structsen_1_1_class_spec" ],
      [ "ClassType", "classsen_1_1_class_type.html", "classsen_1_1_class_type" ],
      [ "ConnectionGuard", "classsen_1_1_connection_guard.html", "classsen_1_1_connection_guard" ],
      [ "CustomType", "classsen_1_1_custom_type.html", "classsen_1_1_custom_type" ],
      [ "CustomTypeRegistry", "classsen_1_1_custom_type_registry.html", "classsen_1_1_custom_type_registry" ],
      [ "Duration", "classsen_1_1_duration.html", "classsen_1_1_duration" ],
      [ "DurationType", "classsen_1_1_duration_type.html", "classsen_1_1_duration_type" ],
      [ "Enumerator", "structsen_1_1_enumerator.html", "structsen_1_1_enumerator" ],
      [ "EnumSpec", "structsen_1_1_enum_spec.html", "structsen_1_1_enum_spec" ],
      [ "EnumTraitsBase", "structsen_1_1_enum_traits_base.html", "structsen_1_1_enum_traits_base" ],
      [ "EnumType", "classsen_1_1_enum_type.html", "classsen_1_1_enum_type" ],
      [ "Event", "classsen_1_1_event.html", "classsen_1_1_event" ],
      [ "EventInfo", "group__obj.html#structsen_1_1_event_info", "group__obj_structsen_1_1_event_info" ],
      [ "EventSpec", "group__types.html#structsen_1_1_event_spec", "group__types_structsen_1_1_event_spec" ],
      [ "FullTypeVisitor", "classsen_1_1_full_type_visitor.html", "classsen_1_1_full_type_visitor" ],
      [ "GradientNoise", "classsen_1_1_gradient_noise.html", "classsen_1_1_gradient_noise" ],
      [ "Guarded", "structsen_1_1_guarded.html", "structsen_1_1_guarded" ],
      [ "HasOperator", "structsen_1_1_has_operator.html", null ],
      [ "HasValueType", "structsen_1_1_has_value_type.html", null ],
      [ "HasValueType< T, std::void_t< typename T::ValueType > >", "structsen_1_1_has_value_type_3_01_t_00_01std_1_1void__t_3_01typename_01_t_1_1_value_type_01_4_01_4.html", null ],
      [ "InputStreamBase", "classsen_1_1_input_stream_base.html", "classsen_1_1_input_stream_base" ],
      [ "InputStreamTemplate", "classsen_1_1_input_stream_template.html", "classsen_1_1_input_stream_template" ],
      [ "IntegralType", "classsen_1_1_integral_type.html", "classsen_1_1_integral_type" ],
      [ "Interest", "classsen_1_1_interest.html", "classsen_1_1_interest" ],
      [ "IsContained", "structsen_1_1_is_contained.html", null ],
      [ "IsVariantMember", "group__templates.html#structsen_1_1_is_variant_member", null ],
      [ "IsVariantMember< T, std::variant< MemberTypes... > >", "structsen_1_1_is_variant_member_3_01_t_00_01std_1_1variant_3_01_member_types_8_8_8_01_4_01_4.html", null ],
      [ "IsVariantMember< T, Var >", "structsen_1_1_is_variant_member_3_01_t_00_01_var_01_4.html", null ],
      [ "LittleEndian", "namespacesen.html#structsen_1_1_little_endian", null ],
      [ "MemberHash", "structsen_1_1_member_hash.html", "structsen_1_1_member_hash" ],
      [ "MetaTypeTrait", "group__traits.html#structsen_1_1_meta_type_trait", null ],
      [ "MetaTypeTrait< Duration >", "structsen_1_1_meta_type_trait_3_01_duration_01_4.html", null ],
      [ "MetaTypeTrait< TimeStamp >", "structsen_1_1_meta_type_trait_3_01_time_stamp_01_4.html", null ],
      [ "Method", "classsen_1_1_method.html", "classsen_1_1_method" ],
      [ "MethodCallInfo", "group__obj.html#structsen_1_1_method_call_info", null ],
      [ "MethodSpec", "structsen_1_1_method_spec.html", "structsen_1_1_method_spec" ],
      [ "MuxedProviderListener", "classsen_1_1_muxed_provider_listener.html", "classsen_1_1_muxed_provider_listener" ],
      [ "NativeObject", "classsen_1_1_native_object.html", "classsen_1_1_native_object" ],
      [ "NativeType", "classsen_1_1_native_type.html", "classsen_1_1_native_type" ],
      [ "NonPropertyRelated", "group__types.html#structsen_1_1_non_property_related", null ],
      [ "NumericType", "classsen_1_1_numeric_type.html", "classsen_1_1_numeric_type" ],
      [ "Object", "classsen_1_1_object.html", "classsen_1_1_object" ],
      [ "ObjectFilter", "classsen_1_1_object_filter.html", "classsen_1_1_object_filter" ],
      [ "ObjectFilterBase", "classsen_1_1_object_filter_base.html", "classsen_1_1_object_filter_base" ],
      [ "ObjectInstanceDiscovery", "group__obj.html#structsen_1_1_object_instance_discovery", "group__obj_structsen_1_1_object_instance_discovery" ],
      [ "ObjectList", "classsen_1_1_object_list.html", "classsen_1_1_object_list" ],
      [ "ObjectMux", "classsen_1_1_object_mux.html", "classsen_1_1_object_mux" ],
      [ "ObjectProvider", "classsen_1_1_object_provider.html", "classsen_1_1_object_provider" ],
      [ "ObjectProviderListener", "classsen_1_1_object_provider_listener.html", "classsen_1_1_object_provider_listener" ],
      [ "ObjectRef", "classsen_1_1_object_ref.html", "classsen_1_1_object_ref" ],
      [ "ObjectRemoval", "group__obj.html#structsen_1_1_object_removal", "group__obj_structsen_1_1_object_removal" ],
      [ "ObjectSource", "classsen_1_1_object_source.html", "classsen_1_1_object_source" ],
      [ "OptionalSpec", "structsen_1_1_optional_spec.html", "structsen_1_1_optional_spec" ],
      [ "OptionalTraitsBase", "structsen_1_1_optional_traits_base.html", null ],
      [ "OptionalType", "classsen_1_1_optional_type.html", "classsen_1_1_optional_type" ],
      [ "OutputStreamTemplate", "classsen_1_1_output_stream_template.html", "classsen_1_1_output_stream_template" ],
      [ "Overloaded", "structsen_1_1_overloaded.html", null ],
      [ "Property", "classsen_1_1_property.html", "classsen_1_1_property" ],
      [ "PropertyGetter", "group__types.html#structsen_1_1_property_getter", "group__types_structsen_1_1_property_getter" ],
      [ "PropertySetter", "group__types.html#structsen_1_1_property_setter", "group__types_structsen_1_1_property_setter" ],
      [ "PropertySpec", "structsen_1_1_property_spec.html", "structsen_1_1_property_spec" ],
      [ "Quantity", "classsen_1_1_quantity.html", "classsen_1_1_quantity" ],
      [ "QuantitySpec", "structsen_1_1_quantity_spec.html", "structsen_1_1_quantity_spec" ],
      [ "QuantityTraits", "group__traits.html#structsen_1_1_quantity_traits", null ],
      [ "QuantityTraits< Duration >", "structsen_1_1_quantity_traits_3_01_duration_01_4.html", null ],
      [ "QuantityTraits< TimeStamp >", "classsen_1_1_quantity_traits_3_01_time_stamp_01_4.html", null ],
      [ "QuantityTraitsBase", "structsen_1_1_quantity_traits_base.html", "structsen_1_1_quantity_traits_base" ],
      [ "QuantityType", "classsen_1_1_quantity_type.html", "classsen_1_1_quantity_type" ],
      [ "RealType", "classsen_1_1_real_type.html", "classsen_1_1_real_type" ],
      [ "RemoteObjectDiscovery", "group__obj.html#structsen_1_1_remote_object_discovery", "group__obj_structsen_1_1_remote_object_discovery" ],
      [ "remove_cvref", "namespacesen.html#structsen_1_1remove__cvref", "namespacesen_structsen_1_1remove__cvref_dup" ],
      [ "ResizableBufferWriter", "classsen_1_1_resizable_buffer_writer.html", "classsen_1_1_resizable_buffer_writer" ],
      [ "Result", "classsen_1_1_result.html", "classsen_1_1_result" ],
      [ "Result< void, E >", "classsen_1_1_result_3_01void_00_01_e_01_4.html", "classsen_1_1_result_3_01void_00_01_e_01_4" ],
      [ "Result< void, std::monostate >", "classsen_1_1_result_3_01void_00_01std_1_1monostate_01_4.html", "classsen_1_1_result_3_01void_00_01std_1_1monostate_01_4" ],
      [ "ScopeGuard", "classsen_1_1_scope_guard.html", "classsen_1_1_scope_guard" ],
      [ "SenClassRelation", "structsen_1_1_sen_class_relation.html", "structsen_1_1_sen_class_relation" ],
      [ "SenClassRelation< const T & >", "structsen_1_1_sen_class_relation_3_01const_01_t_01_6_01_4.html", null ],
      [ "SenClassRelation< const T >", "structsen_1_1_sen_class_relation_3_01const_01_t_01_4.html", null ],
      [ "SenClassRelation< T & >", "structsen_1_1_sen_class_relation_3_01_t_01_6_01_4.html", null ],
      [ "SequenceSpec", "structsen_1_1_sequence_spec.html", "structsen_1_1_sequence_spec" ],
      [ "SequenceTraitsBase", "structsen_1_1_sequence_traits_base.html", null ],
      [ "SequenceType", "classsen_1_1_sequence_type.html", "classsen_1_1_sequence_type" ],
      [ "SerializationTraits", "group__traits.html#structsen_1_1_serialization_traits", null ],
      [ "SerializationTraits< Duration >", "structsen_1_1_serialization_traits_3_01_duration_01_4.html", null ],
      [ "SerializationTraits< TimeStamp >", "structsen_1_1_serialization_traits_3_01_time_stamp_01_4.html", null ],
      [ "ShouldBePassedByValue", "structsen_1_1_should_be_passed_by_value.html", null ],
      [ "ShouldBePassedByValue< ConnId >", "structsen_1_1_should_be_passed_by_value_3_01_conn_id_01_4.html", null ],
      [ "ShouldBePassedByValue< Duration >", "structsen_1_1_should_be_passed_by_value_3_01_duration_01_4.html", null ],
      [ "ShouldBePassedByValue< InterestId >", "structsen_1_1_should_be_passed_by_value_3_01_interest_id_01_4.html", null ],
      [ "ShouldBePassedByValue< MemberHash >", "structsen_1_1_should_be_passed_by_value_3_01_member_hash_01_4.html", null ],
      [ "ShouldBePassedByValue< ObjectId >", "structsen_1_1_should_be_passed_by_value_3_01_object_id_01_4.html", null ],
      [ "ShouldBePassedByValue< ObjectOwnerId >", "structsen_1_1_should_be_passed_by_value_3_01_object_owner_id_01_4.html", null ],
      [ "ShouldBePassedByValue< Quantity< T, D > >", "structsen_1_1_should_be_passed_by_value_3_01_quantity_3_01_t_00_01_d_01_4_01_4.html", null ],
      [ "ShouldBePassedByValue< StrongType< T, D > >", "structsen_1_1_should_be_passed_by_value_3_01_strong_type_3_01_t_00_01_d_01_4_01_4.html", null ],
      [ "ShouldBePassedByValue< StrongTypeBase< T > >", "structsen_1_1_should_be_passed_by_value_3_01_strong_type_base_3_01_t_01_4_01_4.html", null ],
      [ "ShouldBePassedByValue< TimeStamp >", "structsen_1_1_should_be_passed_by_value_3_01_time_stamp_01_4.html", null ],
      [ "SourceLocation", "group__util.html#structsen_1_1_source_location", "group__util_structsen_1_1_source_location" ],
      [ "Span", "classsen_1_1_span.html", "classsen_1_1_span" ],
      [ "StaticVector", "classsen_1_1_static_vector.html", "classsen_1_1_static_vector" ],
      [ "StaticVectorBase", "classsen_1_1_static_vector_base.html", "classsen_1_1_static_vector_base" ],
      [ "StringConversionTraits", "group__traits.html#structsen_1_1_string_conversion_traits", null ],
      [ "StrongType", "classsen_1_1_strong_type.html", "classsen_1_1_strong_type" ],
      [ "StrongTypeBase", "classsen_1_1_strong_type_base.html", "classsen_1_1_strong_type_base" ],
      [ "StructField", "structsen_1_1_struct_field.html", "structsen_1_1_struct_field" ],
      [ "StructSpec", "structsen_1_1_struct_spec.html", "structsen_1_1_struct_spec" ],
      [ "StructTraitsBase", "structsen_1_1_struct_traits_base.html", null ],
      [ "StructType", "classsen_1_1_struct_type.html", "classsen_1_1_struct_type" ],
      [ "Subscription", "structsen_1_1_subscription.html", "structsen_1_1_subscription" ],
      [ "TimeStamp", "classsen_1_1_time_stamp.html", "classsen_1_1_time_stamp" ],
      [ "TimestampType", "classsen_1_1_timestamp_type.html", "classsen_1_1_timestamp_type" ],
      [ "Type", "classsen_1_1_type.html", "classsen_1_1_type" ],
      [ "TypeHandle", "classsen_1_1_type_handle.html", "classsen_1_1_type_handle" ],
      [ "TypeMatchIssue", "group__type__utils.html#structsen_1_1_type_match_issue", "group__type__utils_structsen_1_1_type_match_issue" ],
      [ "TypesDontMatch", "group__type__utils.html#structsen_1_1_types_dont_match", "group__type__utils_structsen_1_1_types_dont_match" ],
      [ "TypesMatch", "group__type__utils.html#structsen_1_1_types_match", "group__type__utils_structsen_1_1_types_match" ],
      [ "TypeVisitor", "classsen_1_1_type_visitor.html", "classsen_1_1_type_visitor" ],
      [ "Unit", "classsen_1_1_unit.html", "classsen_1_1_unit" ],
      [ "UnitRegistry", "classsen_1_1_unit_registry.html", "classsen_1_1_unit_registry" ],
      [ "UnitSpec", "structsen_1_1_unit_spec.html", "structsen_1_1_unit_spec" ],
      [ "Uuid", "classsen_1_1_uuid.html", "classsen_1_1_uuid" ],
      [ "UuidRandomGenerator", "classsen_1_1_uuid_random_generator.html", "classsen_1_1_uuid_random_generator" ],
      [ "Var", "structsen_1_1_var.html", "structsen_1_1_var" ],
      [ "VariantField", "structsen_1_1_variant_field.html", "structsen_1_1_variant_field" ],
      [ "VariantSpec", "structsen_1_1_variant_spec.html", "structsen_1_1_variant_spec" ],
      [ "VariantTraits", "group__traits.html#structsen_1_1_variant_traits", null ],
      [ "VariantTraits< Duration >", "structsen_1_1_variant_traits_3_01_duration_01_4.html", null ],
      [ "VariantTraits< TimeStamp >", "structsen_1_1_variant_traits_3_01_time_stamp_01_4.html", null ],
      [ "VariantTraitsBase", "structsen_1_1_variant_traits_base.html", null ],
      [ "VariantTraitsBaseBase", "structsen_1_1_variant_traits_base_base.html", null ],
      [ "VariantType", "classsen_1_1_variant_type.html", "classsen_1_1_variant_type" ],
      [ "VarInfo", "group__obj.html#structsen_1_1_var_info", "group__obj_structsen_1_1_var_info" ],
      [ "VoidType", "classsen_1_1_void_type.html", "classsen_1_1_void_type" ],
      [ "Writer", "classsen_1_1_writer.html", "classsen_1_1_writer" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< sen::kernel::ParticipantAddr >", "structstd_1_1hash_3_01sen_1_1kernel_1_1_participant_addr_01_4.html", "structstd_1_1hash_3_01sen_1_1kernel_1_1_participant_addr_01_4" ],
      [ "hash<::sen::MemberHash >", "structstd_1_1hash_3_1_1sen_1_1_member_hash_01_4.html", "structstd_1_1hash_3_1_1sen_1_1_member_hash_01_4" ]
    ] ],
    [ "KernelFixture", "class_kernel_fixture.html", "class_kernel_fixture" ]
];