// === casio_calculator.cpp ============================================================================================
//                                               Sen Infrastructure
//                   Released under the Apache License v2.0 (SPDX-License-Identifier Apache-2.0).
//                                    See the LICENSE.txt file for more information.
//                   © Airbus SAS, Airbus Helicopters, and Airbus Defence and Space SAU/GmbH/SAS.
// =====================================================================================================================

// generated code
#include "stl/calculator.stl.h"

// sen
#include "sen/core/base/compiler_macros.h"
#include "sen/core/base/numbers.h"
#include "sen/core/meta/class_type.h"

namespace calculators
{

/// Our implementation of a calculator.
/// We inherit from the CalculatorBase class (generated by Sen).
class CasioCalculator: public CalculatorBase
{
public:
  SEN_NOCOPY_NOMOVE(CasioCalculator)

public:
  using CalculatorBase::CalculatorBase;
  ~CasioCalculator() override = default;

protected:
  /// This is the implementation of the "add" method.
  /// We need to provide an implementation to be able to instantiate this class.
  float32_t addImpl(float32_t a, float32_t b) override
  {
    const auto result = a + b;
    setNextCurrent(result);  // Save the result in our "current" property.
    return result;
  }

  /// Implementation of addWithCurrent.
  float32_t addWithCurrentImpl(float32_t a) override
  {
    // Just call add with what we have in our "current" property.
    return addImpl(a, getCurrent());
  }

  /// Implementation of divide.
  float32_t divideImpl(float32_t a, float32_t b) override
  {
    float32_t result = 0.0f;
    if (b == 0.0f)
    {
      divisionByZero();  // If we divide by zero, emit the event.
    }
    else
    {
      result = a / b;
    }

    // Save the result in our "current" property.
    setNextCurrent(result);
    return result;
  }

  /// Implementation of divideWithCurrent.
  float32_t divideByCurrentImpl(float32_t a) override { return divideImpl(a, getCurrent()); }
};

// With this macro we let Sen know that this package provides our class.
// You need to define this only once in a cpp file.
SEN_EXPORT_CLASS(CasioCalculator)

}  // namespace calculators
