# $schema: ../base/schema.json
include:
  - ../base/shell.yaml

build:
  - name: myComponent
    freqHz: 30
    imports: [aircrafts]
    group: 3
    objects:
      - class: aircrafts.DummyAircraftImpl
        name: myAircraft
        bus: my.tutorial
        speed: 250
        entityType: &theType
          entityKind: 1
          domain: 2
          countryCode: 198
          category: 1
          subcategory: 3
          specific: 0
          extra: 0
        alternateEntityType: *theType
        entityIdentifier:
          entityNumber: 1
          federateIdentifier:
            siteID: 1
            applicationID: 1
