# === standard_test.yaml ===============================================================================================
#                                               Sen Infrastructure
#                   Released under the Apache License v2.0 (SPDX-License-Identifier Apache-2.0).
#                                    See the LICENSE.txt file for more information.
#                   © Airbus SAS, Airbus Helicopters, and Airbus Defence and Space SAU/GmbH/SAS.
# ======================================================================================================================

name: Standard PR Tests

on:
  workflow_call:
    inputs:
      building-main:
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  compute-matrix-jobs:
    name: "Generate build matrix"
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.compute-jobs.outputs.jobs }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - id: compute-jobs
        run: python .github/scripts/generate_matrix_jobs.py --standard-test ${{ inputs.building-main == true && '--target-main' || '' }}
  build:
    name: "Standard Test Job: ${{ matrix.compiler.name }}-${{ matrix.arch }}-${{ matrix.compiler.version }} C++${{ matrix.std }} [${{ matrix.build_type }}]"
    needs: compute-matrix-jobs
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        include: ${{ fromJson(needs.compute-matrix-jobs.outputs.jobs) }}
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Disable for now on local runner
      #
      # - name: Generate daily cache id
      #   shell: bash
      #   run: echo "cache_date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_ENV

      # - name: Cache conan packages
      #   uses: actions/cache@v5
      #   if: always()
      #   env:
      #     cache-name: cache-conan-packages
      #   with:
      #     path: ~/.conan2/p
      #     key: conanp-${{ matrix.os }}-${{ matrix.compiler.name }}-${{ matrix.build_type }}-${{ matrix.compiler.version }}-${{ matrix.std }}-${{ env.cache_date }}
      #     restore-keys: conanp-${{ matrix.os }}-${{ matrix.compiler.name }}-${{ matrix.build_type }}-${{ matrix.compiler.version }}-${{ matrix.std }}-

      - uses: hendrikmuhs/ccache-action@v1.2
        if: runner.os == 'Linux'
        with:
          key: ${{ matrix.os }}-${{ matrix.compiler.name }}-${{ matrix.compiler.version }}-${{ matrix.std }}-${{ matrix.build_type }}
          max-size: 250M
          verbose: 1

      - name: Setup build context
        uses: ./.github/actions/setup_build_context
        with:
          compiler-name: ${{ matrix.compiler.name }}
          compiler-version: ${{ matrix.compiler.version }}
          arch: ${{ matrix.arch }}

      - name: Install additional python dependencies
        shell: bash
        run: pip install -U junitparser

      - name: Compile base libraries
        shell: bash
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          # export ENABLE_EXAMPLES=true
          export ENABLE_TESTS=true
          export ENABLE_COVERAGE=${{ matrix.enable_coverage }}

          conan install . -s:a build_type=${{ matrix.build_type }} --build=missing
          conan build . -s:a build_type=${{ matrix.build_type }}

      - name: Run tests
        shell: bash
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cmake --build build/${{ matrix.compiler.name }}/${{ matrix.build_type }}/ --target run_tests

      # TODO(SEN-1726): Connect App to Airbus Org.
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     files: coverage_reports/coverage.lcov
      #     fail_ci_if_error: true
      #     token: ${{ secrets.CODECOV_TOKEN }}

      - name: Remove unwanted parts from conan cache before backup
        shell: bash
        run: |
          conan cache clean "*" -s -b -d
